### ISSUE TITLE
breadboard variants

### ISSUE THREAD

**Issue by perlchamp** [Move2win/Fritzing-0.9.9.64.pc-Compiled-Build#1]
hello to everyone,
i hope, this is the right way for asking ...

i have an esp32 mini-project (temperature controlled fans).
unfortunately there is only one way to position an esp32 properly on a breadboard so that both pin sides of the esp32 are freely accessible:
you remove a +/- bar from a breadboard, and then connect that breadboard to a full breadboard.
for example, the left pin side of the esp32 can be plugged into the i44-i63 area of ​​the unchanged breadboard and the right pin side into the c44-c63 area of ​​the modified breadboard.
this gives the user at least 2 rows on each side of the esp32 for wiring ;-) ...
Unfortunately, Fritzing does not offer a breadboard with only ONE +/- bar. couldn't this be changed quickly?
that would be really great, also with regard to other (larger) boards.

keep corona away!

so long
pc

**Comment by douglascarlos-dev** [comment]
Adaptador de Pinos para o WiFi ESP8266 ESP-01

**Comment by Move2win** [comment]
Sorry for the late response.
If you want to feedback any Fritzing app issues, you can go either

https://github.com/fritzing/fritzing-app/issues
or
https://forum.fritzing.org/

I'm just sharing a compiled app, the official wants money and force user to donate if they wish to download the compiled app.
I'm not a part of Fritzing dev.
