### ISSUE TITLE
How do we trust this repository?

### ISSUE THREAD

**Issue by pyIronManCoder** [Move2win/Fritzing-0.9.9.64.pc-Compiled-Build#3]
Hello @Move2win
Thanks for this amazing repository, but I was a bit skeptical on downloading this as an md5 hash isn't available for this version online. Could you please tell me where to look up for an md5 hash for this version? Also the publisher shows up as unknown... Could you please clarify...
Thanks

**Comment by Move2win** [comment]
This software(repo) is built based on the official source code on GitHub.
If you are concerned about software safety, you can always build your version from the source code.
The official git repo is at: https://github.com/fritzing/fritzing-app

**Comment by pyIronManCoder** [comment]
Thanks for quick reply, I am a beginner at compiling from source. Could you clarify why it is showing up like this
![image](https://github.com/Move2win/Fritzing-0.9.9.64.pc-Compiled-Build/assets/122616133/4fc5046e-f0ed-49f0-8a35-ab40d54bd466)

**Comment by Move2win** [comment]
This is a Windows problem, every app it doesn't “recognize” could cause this warning to pop up, especially for those downloaded from the internet.

You can just ignore it and click “run anyway.”

**Comment by pyIronManCoder** [comment]
ok thanks a lot
